[meta]
entity = "Prozessdaten"
bo4e_type = "Prozessdaten"
source_group = "SG4"
source_path = "sg4"

[fields]
"dtm[93].c507.d2380" = "gueltigBis"
"ide.c206.d7402" = "vorgangId"
"sts.c556.d9013" = "transaktionsgrund"
"sts.c556_2.d9013" = "transaktionsgrundErgaenzung"
"sts.c556_3.d9013" = "transaktionsgrundErgaenzungBefristeteAnmeldung"

[fields."dtm[93].c507.d2005"]
target = ""
default = "93"

[fields."dtm[93].c507.d2379"]
target = ""
default = "303"

[fields."ide.d7495"]
target = ""
default = "24"

[fields."sts.c601.d9015"]
target = ""
default = "7"
