[meta]
entity = "Geschaeftspartner"
bo4e_type = "Geschaeftspartner"
companion_type = "GeschaeftspartnerEdifact"
source_group = "SG4.SG12"
source_path = "sg4.sg12_z04"
discriminator = "NAD.d3035=Z04"

[fields]
"nad.c059.d3042" = "strasse"
"nad.c059.d3042_3" = "hausnummer"
"nad.c080.d3036" = "nachname"
"nad.c080.d3036_2" = "vorname"
"nad.c080.d3036_5" = "anrede"
"nad.d3164" = "ort"
"nad.d3207" = "land"
"nad.d3251" = "postleitzahl"

[fields."nad.d3035"]
target = ""
default = "Z04"

[companion_fields]
"nad.c059.d3042_2" = "strasseZusatz"
"nad.c059.d3042_4" = "adresszusatz"
"nad.c080.d3036_3" = "namenszusatz1"
"nad.c080.d3036_4" = "namenszusatz2"
"nad.c080.d3045" = "anredeCode"
"nad.c819.d3229" = "region"
"rff[Z46].c506.d1154" = "zeitscheibeRef"

[companion_fields."rff[Z46].c506.d1153"]
target = ""
default = "Z46"
