# EnfgDaten Zuordnung (SG10 within SEQ+Z75)
# CCI/CAV characteristics for EnFG data.

[meta]
entity = "EnfgDaten"
bo4e_type = "EnfgDaten"
companion_type = "EnfgDatenEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_z75.sg10"

[fields]

[companion_fields]
"cci.d7059" = "merkmalCode"
"cci.c240.d7037" = "verringerungStatus"
"cav.c889.d7111" = "privilegierungGrund"
