[meta]
entity = "SteuerbareRessource"
bo4e_type = "SteuerbareRessource"
companion_type = "SteuerbareRessourceEdifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_zb1_zb2"

[fields]
"seq.c286.d1050" = "zeitraumReferenz"

[companion_fields]
