[meta]
entity = "Netzlokation"
bo4e_type = "Netzlokation"
companion_type = "NetzlokationEdifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_z51"
discriminator = "SEQ.d1229=Z51"

[fields]
"seq.c286.d1050" = "zeitraumReferenz"

[fields."seq.d1229"]
target = ""
default = "Z51"

[companion_fields]
