[build]
target = "index.html"
dist = "dist"

[watch]
watch = ["src", "index.html", "style"]

[serve]
address = "127.0.0.1"
port = 3000

[[proxy]]
rewrite = "/api/"
backend = "http://127.0.0.1:8080/api/"

[[proxy]]
rewrite = "/health"
backend = "http://127.0.0.1:8080/health"
