[meta]
entity = "Geschaeftspartner"
bo4e_type = "Geschaeftspartner"
companion_type = "GeschaeftspartnerEdifact"
source_group = "SG4.SG12"
source_path = "sg4.sg12_z04"
discriminator = "NAD.d3035=Z04"

[fields]
"nad.c080.d3036" = "nachname"
"nad.c080.d3036_2" = "vorname"
"nad.c080.d3036_5" = "anrede"
"nad.c059.d3042" = "strasse"
"nad.c059.d3042_3" = "hausnummer"
"nad.d3164" = "ort"
"nad.d3251" = "postleitzahl"
"nad.d3207" = "land"

[fields."nad.0"]
target = ""
default = "Z04"

[companion_fields]
"nad.c080.d3045" = "anredeCode"
"nad.c059.d3042_2" = "strasseZusatz"
"nad.c819.d3229" = "region"
