[meta]
entity = "Produktpaket"
bo4e_type = "Produktpaket"
source_group = "SG4.SG8"
source_path = "sg4.sg8_z79"
discriminator = "SEQ.d1229=Z79"

[fields]
"pia.c212.d7140" = "produktCode"
"seq.c286.d1050" = "produktpaketId"

[fields."pia.0"]
target = ""
default = "5"

[fields."pia.1.1"]
target = ""
default = "Z11"

[fields."seq.0"]
target = ""
default = "Z79"
