[meta]
entity = "Produktpaket"
bo4e_type = "Produktpaket"
source_group = "SG4.SG8"
source_path = "sg4.sg8_z79"
discriminator = "SEQ.0.0=Z79"

[fields]
"pia.1.0" = "produktCode"
"seq.1" = "produktpaketId"

[fields."pia.0"]
target = ""
default = "5"

[fields."pia.1.1"]
target = ""
default = "Z11"

[fields."seq.0"]
target = ""
default = "Z79"
