[meta]
entity = "ProduktpaketPriorisierung"
bo4e_type = "ProduktpaketPriorisierung"
source_group = "SG4.SG8"
source_path = "sg4.sg8_zh0"
discriminator = "SEQ.0.0=ZH0"

[fields]
"seq.1" = "produktpaketReferenz"

[fields."seq.0"]
target = ""
default = "ZH0"
