[meta]
entity = "ProduktpaketPriorisierung"
bo4e_type = "ProduktpaketPriorisierung"
source_group = "SG4.SG8"
source_path = "sg4.sg8_zh0"
discriminator = "SEQ.d1229=ZH0"

[fields]
"seq.c286.d1050" = "produktpaketReferenz"

[fields."seq.d1229"]
target = ""
default = "ZH0"
