# ProduktpaketPriorisierung Zuordnung (SG10 within SEQ+ZH0) for PID 55014.
# CCI/CAV characteristics for ProduktpaketPriorisierung.

[meta]
entity = "ProduktpaketPriorisierung"
bo4e_type = "ProduktpaketPriorisierung"
source_group = "SG4.SG8:3.SG10"
source_path = "sg4.sg8_zh0.sg10"

[fields]
"cav.0.0" = "priorisierungsCode"
"cci.2.0" = "merkmalCode"
"cci.1.0" = "gemesseneDimension"
