[meta]
entity = "Prozessdaten"
bo4e_type = "Prozessdaten"
source_group = "SG4.SG6"
source_path = "sg4.sg6"
discriminator = "RFF.c506.d1153=Z60"

[fields]
"rff.c506.d1154" = "geplantesPaket"

[fields."rff.c506.d1153"]
target = ""
default = "Z60"
