[meta]
entity = "Netzlokation"
bo4e_type = "Netzlokation"
companion_type = "NetzlokationEdifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_zd7"
discriminator = "SEQ.d1229=ZD7"

[fields]
"seq.c286.d1050" = "zeitraumReferenz"

[fields."seq.d1229"]
target = ""
default = "ZD7"

[companion_fields]
"rff.c506.d1154" = "referenzNetzlokation"

[companion_fields."rff.c506.d1153"]
target = ""
default = "Z32"
