[meta]
entity = "Marktlokation"
bo4e_type = "Marktlokation"
companion_type = "MarktlokationEdifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_z98"
discriminator = "SEQ.d1229=Z98"

[fields]

[fields."seq.d1229"]
target = ""
default = "Z98"
