# Marktlokation Zuordnung (SG10 within SEQ+Z98) for PID 55013.
# CCI/CAV Prognosegrundlage data, merges into entity "Marktlokation".
#
# CCI+Z42++ZB9/ZD3                   -> merkmalCode (Prognosegrundlage)
# CAV+E02/E14                        -> prognosegrundlage

[meta]
entity = "Marktlokation"
bo4e_type = "Marktlokation"
companion_type = "MarktlokationEdifact"
source_group = "SG4.SG8:1.SG10"
source_path = "sg4.sg8_z98.sg10"

[fields]

[companion_fields]
"cci.2.0" = "merkmalCode"
"cav.0.0" = "prognosegrundlage"
