[meta]
entity = "Marktlokation"
bo4e_type = "Marktlokation"
source_group = "SG4.SG5:1"
source_path = "sg4.sg5_z16"
discriminator = "LOC.d3227=Z16"

[fields]
"loc.c517.d3225" = "marktlokationsId"

[fields."loc.0"]
target = ""
default = "Z16"
