# Marktlokation Zuordnung Betriebszustand (SG10 within SEQ+Z98) for PID 55013.
# CCI Betriebszustand der Marktlokation, merges into entity "Marktlokation".
#
# CCI+Z42++ZD3/ZB9             -> Betriebszustand (Z42 = Klassentyp, ZD3/ZB9 = Merkmal)

[meta]
entity = "Marktlokation"
bo4e_type = "Marktlokation"
companion_type = "MarktlokationEdifact"
source_group = "SG4.SG8:1.SG10"
source_path = "sg4.sg8_z98.sg10"
discriminator = "CCI.0.0=Z42"

[fields]

[companion_fields]
"cci.2.0" = "betriebszustand"

[companion_fields."cci.0.0"]
target = ""
default = "Z42"
