# Marktlokation Zuordnung Spannungsebene (SG10 within SEQ+Z98) for PID 55013.
# CCI/CAV Spannungsebene, merges into entity "Marktlokation".
#
# CCI+++E03                    -> Spannungsebene qualifier
# CAV+E06                      -> Niederspannung (E03..E06)

[meta]
entity = "Marktlokation"
bo4e_type = "Marktlokation"
companion_type = "MarktlokationEdifact"
source_group = "SG4.SG8:1.SG10"
source_path = "sg4.sg8_z98.sg10"
discriminator = "CCI.c240.d7037=E03"

[fields]

[companion_fields]
"cav.c889.d7111" = "spannungsebene"

[companion_fields."cci.c240.d7037"]
target = ""
default = "E03"
