[meta]
entity = "Messlokation"
bo4e_type = "Messlokation"
source_group = "SG4.SG5:4"
source_path = "sg4.sg5_z17"
discriminator = "LOC.d3227=Z17"

[fields]
"loc.c517.d3225" = "messlokationsId"

[fields."loc.d3227"]
target = ""
default = "Z17"
