[meta]
entity = "Messlokation"
bo4e_type = "Messlokation"
source_group = "SG4.SG5"
source_path = "sg4.sg5_z17"
discriminator = "LOC.0.0=Z17"

[fields]
"loc.1.0" = "messlokationsId"

[fields."loc.0"]
target = ""
default = "Z17"
