[meta]
entity = "Netzlokation"
bo4e_type = "Netzlokation"
source_group = "SG4.SG5"
source_path = "sg4.sg5_z18"
discriminator = "LOC.0.0=Z18"

[fields]
"loc.1.0" = "netzlokationsId"

[fields."loc.0"]
target = ""
default = "Z18"
