[meta]
entity = "Netzlokation"
bo4e_type = "Netzlokation"
source_group = "SG4.SG5:0"
source_path = "sg4.sg5_z18"
discriminator = "LOC.d3227=Z18"

[fields]
"loc.c517.d3225" = "netzlokationsId"

[fields."loc.0"]
target = ""
default = "Z18"
