# Kundenname des NB (informative customer name of the network operator) for PID 55013.
#
# Source: SG4.SG12 -> NAD+Z67 (Informativer Kundenname des NB)
# Name segments: C082 ID, C058 Zusatzinfo, C080 name with format code.
# NAD+Z67+<ID>+<Zusatzinfo>+<Name:Vorname:::Anrede:Code>

[meta]
entity = "KundeDesNb"
bo4e_type = "KundeDesNb"
companion_type = "KundeDesNbEdifact"
source_group = "SG4.SG12"
source_path = "sg4.sg12_z67"
discriminator = "NAD.d3035=Z67"

[fields]
"nad.d3035" = { target = "", default = "Z67" }
"nad.c082.d3039" = "identifikation"
"nad.c080.d3036" = "nachname"
"nad.c080.d3036_2" = "vorname"
"nad.c080.d3036_5" = "anrede"

[companion_fields]
"nad.c058.d3124" = "zusatzinfo"
"nad.c080.d3036_3" = "nameZeile3"
"nad.c080.d3036_4" = "nameZeile4"
"nad.c080.d3045" = "anredeCode"
