# Kunde des LF (informative customer name of the supplier) for PID 55013.
#
# Source: SG4.SG12 -> NAD+Z65 (Informativer Kunde des LF)
# Name segments: C082 ID, C058 Zusatzinfo, C080 name with format code.
# NAD+Z65+<ID>+<Zusatzinfo>+<Name:Vorname:::Anrede:Code>

[meta]
entity = "KundeDesLf"
bo4e_type = "KundeDesLf"
companion_type = "KundeDesLfEdifact"
source_group = "SG4.SG12"
source_path = "sg4.sg12_z65"
discriminator = "NAD.0.0=Z65"

[fields]
"nad.0" = { target = "", default = "Z65" }
"nad.1.0" = "identifikation"
"nad.3.0" = "nachname"
"nad.3.1" = "vorname"
"nad.3.4" = "anrede"

[companion_fields]
"nad.2.0" = "zusatzinfo"
"nad.3.2" = "nameZeile3"
"nad.3.3" = "nameZeile4"
"nad.3.5" = "anredeCode"
