# Kunde des LF (informative customer name of the supplier) for PID 55013.
#
# Source: SG4.SG12 -> NAD+Z65 (Informativer Kunde des LF)
# Name segments: C082 ID, C058 Zusatzinfo, C080 name with format code.
# NAD+Z65+<ID>+<Zusatzinfo>+<Name:Vorname:::Anrede:Code>

[meta]
entity = "KundeDesLf"
bo4e_type = "KundeDesLf"
companion_type = "KundeDesLfEdifact"
source_group = "SG4.SG12"
source_path = "sg4.sg12_z65"
discriminator = "NAD.d3035=Z65"

[fields]
"nad.d3035" = { target = "", default = "Z65" }
"nad.c082.d3039" = "identifikation"
"nad.c080.d3036" = "nachname"
"nad.c080.d3036_2" = "vorname"
"nad.c080.d3036_5" = "anrede"

[companion_fields]
"nad.c058.d3124" = "zusatzinfo"
"nad.c080.d3036_3" = "nameZeile3"
"nad.c080.d3036_4" = "nameZeile4"
"nad.c080.d3045" = "anredeCode"
