# Korrespondenzanschrift des Kunden des LF for PID 55013.
#
# Source: SG4.SG12 -> NAD+Z66 (Informative Korrespondenzanschrift des Kunden des LF)
# Full address: C082 ID, C058 Zusatzinfo, C080 name, C059 street, city, postal code, country, C819 region.
# NAD+Z66+<ID>+<Zusatzinfo>+<Name:Vorname:::Anrede:Code>+<Strasse>+<Ort>+<Region>+<PLZ>+<Land>

[meta]
entity = "KorrespondenzanschriftKundeLf"
bo4e_type = "KorrespondenzanschriftKundeLf"
companion_type = "KorrespondenzanschriftKundeLfEdifact"
source_group = "SG4.SG12"
source_path = "sg4.sg12_z66"
discriminator = "NAD.d3035=Z66"

[fields]
"nad.d3035" = { target = "", default = "Z66" }
"nad.c082.d3039" = "identifikation"
"nad.c080.d3036" = "nachname"
"nad.c080.d3036_2" = "vorname"
"nad.c080.d3036_5" = "anrede"
"nad.c059.d3042" = "strasse"
"nad.c059.d3042_3" = "hausnummer"
"nad.d3164" = "ort"
"nad.d3251" = "postleitzahl"
"nad.d3207" = "land"

[companion_fields]
"nad.c058.d3124" = "zusatzinfo"
"nad.c080.d3036_3" = "nameZeile3"
"nad.c080.d3036_4" = "nameZeile4"
"nad.c080.d3045" = "anredeCode"
"nad.c059.d3042_2" = "strasseZusatz"
"nad.c059.d3042_4" = "strasseZeile4"
"nad.c819.d3229" = "region"
