[meta]
entity = "SteuerbareRessource"
bo4e_type = "SteuerbareRessource"
source_group = "SG4.SG5:3"
source_path = "sg4.sg5_z19"
discriminator = "LOC.d3227=Z19"

[fields]
"loc.c517.d3225" = "steuerbareRessourceId"

[fields."loc.0"]
target = ""
default = "Z19"
