[meta]
entity = "TechnischeRessource"
bo4e_type = "TechnischeRessource"
source_group = "SG4.SG5:2"
source_path = "sg4.sg5_z20"
discriminator = "LOC.0.0=Z20"

[fields]
"loc.1.0" = "technischeRessourceId"

[fields."loc.0"]
target = ""
default = "Z20"
