[meta]
entity = "Netzlokation"
bo4e_type = "Netzlokation"
companion_type = "NetzlokationEdifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8"

[fields]
"seq.c286.d1050" = "zeitraumReferenz"

[companion_fields]
"seq.d1229" = "seqQualifier"
