[meta]
entity = "Prozessdaten"
bo4e_type = "Prozessdaten"
source_group = "SG4"
source_path = "sg4"

[fields]
"ide.c206.d7402" = "vorgangId"
"sts[7].c556.d9013" = "transaktionsgrund"
"sts[E01].c556.d9013" = "pruefschrittCode"
"sts[E01].c556.d1131" = "ebdNummer"

[fields."ide.d7495"]
target = ""
default = "24"

[fields."sts[7].c601.d9015"]
target = ""
default = "7"

[fields."sts[E01].c601.d9015"]
target = ""
default = "E01"
