[meta]
entity = "SteuerbareRessource"
bo4e_type = "SteuerbareRessource"
companion_type = "SteuerbareRessourceEdifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_z62"
discriminator = "SEQ.d1229=Z62"

[fields]
"seq.c286.d1050" = "zeitraumReferenz"

[fields."seq.d1229"]
target = ""
default = "Z62"

[companion_fields]
