# Marktlokation (LOC+Z16) for PID 55002.
#
# LOC+Z16+<Marktlokations-ID>
# The ID identifies a Marktlokation. SG8 SEQ+Z98 can reference it.

[meta]
entity = "Marktlokation"
bo4e_type = "Marktlokation"
source_group = "SG4.SG5"
source_path = "sg4.sg5_z16"
discriminator = "LOC.d3227=Z16"

[fields]
"loc.c517.d3225" = "marktlokationsId"

[fields."loc.d3227"]
target = ""
default = "Z16"
