# Marktlokation informative data (SEQ+Z98) for PID 55002.
# Merges into entity "Marktlokation" via deep-merge.
#
# SEQ+Z98+<Zeitraum-Ref>  (Informative Daten der Marktlokation)

[meta]
entity = "Marktlokation"
bo4e_type = "Marktlokation"
companion_type = "MarktlokationEdifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_z98"
discriminator = "SEQ.d1229=Z98"

[fields]
"seq.c286.d1050" = "zeitraumReferenz"

[fields."seq.d1229"]
target = ""
default = "Z98"
