# TechnischeRessource (LOC+Z20) for PID 55002.
#
# LOC+Z20+D417MLM8164

[meta]
entity = "TechnischeRessource"
bo4e_type = "TechnischeRessource"
source_group = "SG4.SG5"
source_path = "sg4.sg5_z20"
discriminator = "LOC.d3227=Z20"

[fields]
"loc.c517.d3225" = "technischeRessourceId"

[fields."loc.0"]
target = ""
default = "Z20"
