[meta]
entity = "Netzlokation"
bo4e_type = "Netzlokation"
companion_type = "NetzlokationEdifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_z71"
discriminator = "SEQ.d1229=Z71"

[fields]
"seq.c286.d1050" = "zeitraumReferenz"

[fields."seq.d1229"]
target = ""
default = "Z71"

[companion_fields]
"pia.c212.d7140" = "artikelId"
"pia.c212.d7143" = "artikelIdTyp"

[companion_fields."pia.d4347"]
target = ""
default = "Z02"
