# Marktlokation Zuordnung (SG10 within SEQ+Z98) for PID 55035.
# CCI/CAV Prognosegrundlage data.

[meta]
entity = "Marktlokation"
bo4e_type = "Marktlokation"
companion_type = "MarktlokationEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_z98.sg10"

[fields]

[companion_fields]
"cci.2.0" = "merkmalCode"
"cav.0.0" = "prognosegrundlage"
