[meta]
entity = "Marktlokation"
bo4e_type = "Marktlokation"
source_group = "SG4.SG5"
source_path = "sg4.sg5_z16"
discriminator = "LOC.0.0=Z16"

[fields]
"loc.1.0" = "marktlokationsId"

[fields."loc.0"]
target = ""
default = "Z16"
