# Marktlokation Zuordnung (SG10 within SEQ+Z98) for PID 55035.
# CCI/CAV zugeordneter Marktpartner data (rep 0: CCI+++ZB3).

[meta]
entity = "Marktlokation"
bo4e_type = "Marktlokation"
companion_type = "MarktlokationEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_z98.sg10"
discriminator = "CCI.c240.d7037=ZB3"

[fields]

[companion_fields]
"cci.c240.d7037" = "merkmalCode"
"cav[Z90].c889.d1131" = "prognosegrundlageMpId"
"cav[Z91].c889.d1131" = "zugeordneterMp"
"cav[Z91].c889.d7110" = "msbEigenschaft"
"cav[Z91].c889.d7110_2" = "zuordnungReferenz"

[companion_fields."cav[Z90].c889.d7111"]
target = ""
default = "Z90"

[companion_fields."cav[Z91].c889.d7111"]
target = ""
default = "Z91"
