# Marktlokation Zuordnung (SG10 within SEQ+Z98) for PID 55035.
# CCI Regelzone (CCI+Z36++ZD0). No CAV in this rep.

[meta]
entity = "Marktlokation"
bo4e_type = "Marktlokation"
companion_type = "MarktlokationEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_z98.sg10"
discriminator = "CCI.c240.d7037=ZD0"

[fields]

[companion_fields]
"cci.d7059" = "regelzoneKlassentyp"

[companion_fields."cci.c240.d7037"]
target = ""
default = "ZD0"
