# Netzlokation Zuordnung (SG10 within SEQ+ZD7) for PID 55035.
# CCI/CAV rep 1: CCI+++ZB3, zugeordneter Marktpartner.

[meta]
entity = "Netzlokation"
bo4e_type = "Netzlokation"
companion_type = "NetzlokationEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_zd7.sg10"
discriminator = "CCI.c240.d7037=ZB3"

[fields]

[companion_fields]
"cav[Z91].c889.d1131" = "zugeordneterMp"
"cav[Z91].c889.d7110" = "msbEigenschaft"

[companion_fields."cci.c240.d7037"]
target = ""
default = "ZB3"

[companion_fields."cav[Z91].c889.d7111"]
target = ""
default = "Z91"
