# Marktlokation Mengenangabe (SG9 within SEQ+Z98) for PID 55035.
# QTY segment data, merges into entity "Marktlokation".
#
# QTY+31:<Mengenangabe>:KWH  â†’ Jahresverbrauchsprognose

[meta]
entity = "Marktlokation"
bo4e_type = "Marktlokation"
companion_type = "MarktlokationEdifact"
source_group = "SG4.SG8.SG9"
source_path = "sg4.sg8_z98.sg9"

[fields]

[companion_fields]
"qty.c186.d6060" = "mengenangabe"

[companion_fields."qty.c186.d6063"]
target = ""
default = "31"

[companion_fields."qty.c186.d6411"]
target = ""
default = "KWH"
