# TechnischeRessource Lastprofil/Klimazone info (SEQ+ZG2) for PID 55035.
# Merges into entity "TechnischeRessource" via deep-merge.
#
# SEQ+ZG2+<Zeitraum-Ref>  (Informative Profilschardaten)

[meta]
entity = "TechnischeRessource"
bo4e_type = "TechnischeRessource"
companion_type = "TechnischeRessourceEdifact"
source_group = "SG4.SG8"
source_path = "sg4.sg8_zg2"
discriminator = "SEQ.d1229=ZG2"

[fields]

[companion_fields]
"seq.d1229" = "seqQualifierZG2"
