# Zaehler Messwerterfassung Zuordnung (SG10 within SEQ+ZF5) for PID 55035.
# CCI/CAV rep 1: CCI+++E12, Messwerterfassung an der Zaehleinrichtung.

[meta]
entity = "Zaehler"
bo4e_type = "Zaehler"
companion_type = "ZaehlerEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_zf5.sg10"
discriminator = "CCI.c240.d7037=E12"

[fields]

[companion_fields]
"cav.c889.d7111" = "messwerterfassungCode"

[companion_fields."cci.2.0"]
target = ""
default = "E12"
