# Marktlokation Verbrauchsart Zuordnung (SG10 within SEQ+ZE5) for PID 55035.
# CCI/CAV rep 0: CCI+Z17, Stromverbrauchsart. 3-4 CAVs.

[meta]
entity = "Marktlokation"
bo4e_type = "Marktlokation"
companion_type = "MarktlokationEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_ze5.sg10"

[fields]

[companion_fields]
"cav[Z64].c889.d7111" = "verbrauchsartCode"
"cav[Z65].c889.d7111" = "eMobilitaetCode"
"cav[Z63].c889.d7111" = "verbrauchsartCode2"
"cav[Z57].c889.d7111" = "verbrauchsartCode3"

[companion_fields."cci.d7059"]
target = ""
default = "Z17"
