# Zaehler Kommunikationseinrichtung Zuordnung (SG10 within SEQ+ZF5) for PID 55035.
# CCI/CAV rep 0: CCI+++E13, Kommunikationseinrichtung.

[meta]
entity = "Zaehler"
bo4e_type = "Zaehler"
companion_type = "ZaehlerEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_zf5.sg10"
discriminator = "CCI.c240.d7037=E13"

[fields]

[companion_fields]
"cav[MME].c889.d7111" = "kommunikationseinrichtungTyp"
"cav[MME].c889.d7110" = "kommunikationseinrichtungWert"
"cav[Z30].c889.d7111" = "geraeteId"
"cav[Z30].c889.d7110" = "geraeteNummer"

[companion_fields."cci.c240.d7037"]
target = ""
default = "E13"
