# SteuerbareRessource Konfiguration Zuordnung (SG10 within SEQ+ZF2) for PID 55035.
# CCI/CAV rep 1: CCI+++ZA8, Geraeteeigenschaft.

[meta]
entity = "SteuerbareRessource"
bo4e_type = "SteuerbareRessource"
companion_type = "SteuerbareRessourceEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_zf2.sg10"
discriminator = "CCI.c240.d7037=ZA8"

[fields]

[companion_fields."cci.c240.d7037"]
target = ""
default = "ZA8"
