# TechnischeRessource Mengenangabe (SG9 within SEQ+ZF0) for PID 55035.
# QTY segment data, merges into entity "TechnischeRessource".
#
# QTY+Z42:<Menge>:KWH  â†’ Mengenangabe

[meta]
entity = "TechnischeRessource"
bo4e_type = "TechnischeRessource"
companion_type = "TechnischeRessourceEdifact"
source_group = "SG4.SG8.SG9"
source_path = "sg4.sg8_zf0.sg9"

[fields]

[companion_fields]
"qty.c186.d6060" = "mengenangabe"

[companion_fields."qty.c186.d6063"]
target = ""
default = "Z42"

[companion_fields."qty.c186.d6411"]
target = ""
default = "KWH"
