# Marktlokation Zaehlerausstattung Zuordnung (SG10 within SEQ+ZE4) for PID 55035.
# CCI/CAV rep 1: CCI+++ZA8, Geraeteeigenschaft.

[meta]
entity = "Marktlokation"
bo4e_type = "Marktlokation"
companion_type = "MarktlokationEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_ze4.sg10"
discriminator = "CCI.c240.d7037=ZA8"

[fields]

[companion_fields."cci.c240.d7037"]
target = ""
default = "ZA8"
