# TechnischeRessource Klimazone Zuordnung (SG10 within SEQ+ZG2) for PID 55035.
# CCI/CAV rep 2: CCI+Z99, Klimazone.

[meta]
entity = "TechnischeRessource"
bo4e_type = "TechnischeRessource"
companion_type = "TechnischeRessourceEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_zg2.sg10"
discriminator = "CCI.d7059=Z99"

[fields]

[companion_fields]
"cci.c240.d7037" = "klimazoneId"
"cci.c240.d1131" = "dienstanbieter"
"cci.c240.d3055" = "codelisteKennung"

[companion_fields."cci.d7059"]
target = ""
default = "Z99"
