# SteuerbareRessource Konfiguration Zuordnung (SG10 within SEQ+ZF2) for PID 55035.
# CCI/CAV rep 0: CCI+Z52++SZD, Schaltzeitdefinition.

[meta]
entity = "SteuerbareRessource"
bo4e_type = "SteuerbareRessource"
companion_type = "SteuerbareRessourceEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_zf2.sg10"
discriminator = "CCI.d7059=Z52"

[fields]

[companion_fields]
"cci.d7059" = "klassentypCode"
"cci.c240.d7037" = "definitionsCode"
