# Messlokation Zaehler/Geraete Zuordnung (SG10 within SEQ+ZF0) for PID 55035.
# CCI/CAV rep 1: CCI+Z63, Information zu weiteren technischen Einrichtungen.

[meta]
entity = "Messlokation"
bo4e_type = "Messlokation"
companion_type = "MesslokationEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_zf0.sg10"
discriminator = "CCI.0.0=Z63"

[fields]

[companion_fields]
"cav.0.0" = "zaehlerGeraeteCode"

[companion_fields."cci.0.0"]
target = ""
default = "Z63"
