# TechnischeRessource weitere Einrichtungen Zuordnung (SG10 within SEQ+ZF0) for PID 55035.
# CCI/CAV rep 1: CCI+Z63, Information zu weiteren technischen Einrichtungen.

[meta]
entity = "TechnischeRessource"
bo4e_type = "TechnischeRessource"
companion_type = "TechnischeRessourceEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_zf0.sg10"
discriminator = "CCI.d7059=Z63"

[fields]

[companion_fields]
"cav.c889.d7111" = "zaehlerGeraeteCode"

[companion_fields."cci.d7059"]
target = ""
default = "Z63"
