# TechnischeRessource Klimazone Zuordnung (SG10 within SEQ+ZG2) for PID 55035.
# CCI/CAV rep 2: CCI+Z99, Klimazone.

[meta]
entity = "TechnischeRessource"
bo4e_type = "TechnischeRessource"
companion_type = "TechnischeRessourceEdifact"
source_group = "SG4.SG8.SG10"
source_path = "sg4.sg8_zg2.sg10"
discriminator = "CCI.0.0=Z99"

[fields]

[companion_fields]
"cci.2.0" = "klimazoneId"
"cci.2.1" = "dienstanbieter"
"cci.2.2" = "codelisteKennung"

[companion_fields."cci.0.0"]
target = ""
default = "Z99"
