[meta]
entity = "TechnischeRessource"
bo4e_type = "TechnischeRessource"
source_group = "SG4.SG5"
source_path = "sg4.sg5_z20"
discriminator = "LOC.d3227=Z20"

[fields]
"loc.c517.d3225" = "technischeRessourceId"

[fields."loc.d3227"]
target = ""
default = "Z20"
