# Ansprechpartner (Kunde des LF) mapping for PID 55001.
#
# Source: SG4.SG12 -> NAD+Z09 (Kunde des Lieferanten)
# Name, Vorname, and Anrede from C080 composite.
# NAD+Z09+++Muster:Max:::Herr:Z01  -> nachname, vorname, anrede

[meta]
entity = "Ansprechpartner"
bo4e_type = "Ansprechpartner"
companion_type = "AnsprechpartnerEdifact"
source_group = "SG4.SG12"
source_path = "sg4.sg12_z09"
discriminator = "NAD.d3035=Z09"

[fields]
"nad.d3035" = { target = "", default = "Z09" }
"nad.c080.d3036" = "nachname"
"nad.c080.d3036_2" = "vorname"
"nad.c080.d3036_5" = "anrede"

[companion_fields]
"nad.c080.d3036_3" = "namenszusatz1"
"nad.c080.d3036_4" = "namenszusatz2"
"nad.c080.d3045" = "anredeCode"
