# ProduktpaketPriorisierung Zuordnung (SG10 within SEQ+ZH0) for PID 55001.
# CCI/CAV characteristics, merges into entity "ProduktpaketPriorisierung".
#
# CCI+Z65+++Z02  -> merkmal_code (D7059 Umsetzungsgradvorgabe),
#                   relevanz_zuordnung_lf (C240.D7037 Merkmal Code, Z01/Z02)
# CAV+Z75       -> prioritaet (C889.7111 Priorisierung erforderliches Produktpaket)

[meta]
entity = "ProduktpaketPriorisierung"
bo4e_type = "ProduktpaketPriorisierung"
companion_type = "ProduktpaketPriorisierungEdifact"
source_group = "SG4.SG8:1.SG10"
source_path = "sg4.sg8_zh0.sg10"

[fields]

[companion_fields]
"cci.d7059" = "merkmalCode"
"cci.d4051" = "relevanzZuordnungLf"
"cav.c889.d7111" = "prioritaet"
