# Produktpaket Zuordnung (SG10 within SEQ+Z79) for PID 55001.
# CCI/CAV characteristics, merges into entity "Produktpaket".
#
# CCI+Z66               -> merkmal_code (D7059 Produkteigenschaft)
# CAV+ZH9:::XXXXXXXXXX  -> produkteigenschaft_code (D7110 Merkmalswert, Code der Produkteigenschaft)
# CAV+ZV4:::XXXX        -> produktdetail_wert (D7110 Merkmalswert, Wertedetails zum Produkt)

[meta]
entity = "Produktpaket"
bo4e_type = "Produktpaket"
companion_type = "ProduktpaketEdifact"
source_group = "SG4.SG8:0.SG10"
source_path = "sg4.sg8_z79.sg10"

[fields]

[companion_fields]
"cci.d7059" = "merkmalCode"
"cav[ZH9].c889.d7110" = "produkteigenschaftCode"
"cav[ZV4].c889.d7110" = "produktdetailWert"

[companion_fields."cav[ZH9].c889.d7111"]
target = ""
default = "ZH9"

[companion_fields."cav[ZV4].c889.d7111"]
target = ""
default = "ZV4"
