[meta]
entity = "Messlokation"
bo4e_type = "bo4e::Messlokation"
companion_type = "MesslokationEdifact"
source_group = "SG8"
source_path = "sg4.sg8_z79"
discriminator = "seq.d1245.qualifier == 'Z02'"

[fields]
"loc.c517.d3225" = "messlokations_id"
