[meta]
entity = "Tranche"
bo4e_type = "Tranche"
source_group = "SG4.SG5"
source_path = "sg4.sg5_z21"
discriminator = "LOC.d3227=Z21"

[fields]
"loc.c517.d3225" = "trancheId"

[fields."loc.0"]
target = ""
default = "Z21"
