[meta]
entity = "Geschaeftspartner"
bo4e_type = "bo4e::Geschaeftspartner"
companion_type = "GeschaeftspartnerEdifact"
source_group = "SG2"

[fields]
"nad.d3035" = "qualifier"
"nad.c082.d3039" = "partner_id"
"nad.c058.d3124" = "name_1"
"nad.d3164" = "city"
"nad.d3251" = "postcode"
