[meta]
entity = "Geschaeftspartner"
bo4e_type = "Geschaeftspartner"
companion_type = "GeschaeftspartnerEdifact"
source_group = "SG4.SG12"
source_path = "sg4.sg12"

[fields]
"nad.c082.d3039" = "identifikation"
"nad.c080.d3036" = "nachname"
"nad.c080.d3036_2" = "vorname"
"nad.c080.d3036_5" = "anrede"
"nad.c058.d3124" = "zusatzinfo"
"nad.c059.d3042" = "strasse"
"nad.c059.d3042_3" = "hausnummer"
"nad.d3164" = "ort"
"nad.d3251" = "postleitzahl"
"nad.d3207" = "land"
"nad.c819.d3229" = "region"

[companion_fields]
"nad.d3035" = "nad_qualifier"
"nad.c082.d1131" = "codelist_code"
"nad.c082.d3055" = "codepflege_code"
"nad.c059.d3042_2" = "strasseZusatz"
"nad.c059.d3042_4" = "adresszusatz"
"nad.c080.d3036_3" = "namenszusatz1"
"nad.c080.d3036_4" = "namenszusatz2"
"nad.c080.d3045" = "anredeCode"
"rff[Z46].c506.d1154" = "zeitscheibeRef"

[companion_fields."rff[Z46].c506.d1153"]
target = ""
default = "Z46"
